release: python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py seed_tools && python manage.py seed_demo_data
web: gunicorn raise_project.wsgi --log-file -
