# Generated by Django 6.0.1 on 2026-05-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='share_as_example',
            field=models.BooleanField(default=True, help_text='If True, this activity appears anonymized in the institutional Use Cases library.'),
        ),
    ]
