# Generated by Django 6.0.1 on 2026-05-08 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_set_share_as_example_default_false'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointcomment',
            name='resolved',
            field=models.BooleanField(default=False, help_text='Whether the discussion this comment belongs to has been marked resolved.'),
        ),
        migrations.AddField(
            model_name='checkpointcomment',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkpointcomment',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_checkpoint_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
