# Generated by Django 6.0.1 on 2026-05-10 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_comment_resolved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('checkpoint_completed', 'Checkpoint completed'), ('comment_added', 'Comment added'), ('verification_run', 'Verification run'), ('invite_received', 'Collaboration invite received'), ('invite_accepted', 'Collaboration invite accepted'), ('invite_declined', 'Collaboration invite declined')], max_length=40),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('faculty_advisor', 'Faculty advisor'), ('student_collaborator', 'Student collaborator')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.project')),
                ('to_user', models.ForeignKey(blank=True, help_text='Resolved when the invitee has an account at the time of send, or when they sign up later with this email.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_user', 'status'], name='api_invitat_to_user_c9d11e_idx'), models.Index(fields=['to_email', 'status'], name='api_invitat_to_emai_9ff09a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('project', 'to_email', 'role'), name='unique_pending_invitation_per_email_role')],
            },
        ),
    ]
