# Generated by Django 6.0.1 on 2026-05-17 02:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('activity_created', 'Activity created'), ('activity_updated', 'Activity updated'), ('checkpoint_completed', 'Checkpoint completed'), ('checkpoint_reopened', 'Checkpoint reopened'), ('decision_logged', 'Decision logged'), ('comment_added', 'Comment added'), ('comment_resolved', 'Comment resolved'), ('comment_reopened', 'Comment reopened'), ('verification_run', 'Verification run'), ('shared_as_example', 'Shared as example'), ('unshared_as_example', 'Unshared as example'), ('invite_sent', 'Invitation sent'), ('invite_accepted', 'Invitation accepted'), ('invite_declined', 'Invitation declined')], max_length=40)),
                ('summary', models.CharField(help_text='Human-readable one-line description shown in the timeline.', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra structured detail (e.g. verification verdict, changed fields).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered the event. Null if the actor account was removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('checkpoint', models.ForeignKey(blank=True, help_text='Checkpoint the event concerns, when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.checkpoint')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='api_activit_project_629479_idx')],
            },
        ),
    ]
