# Generated by Django 6.0.1 on 2026-06-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_backfill_activity_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('research', 'Research'), ('teaching', 'Teaching'), ('grading', 'Grading'), ('admin', 'Admin')], default=None, help_text='Activity category used to group activities on the dashboard. Null means the user has not categorized this activity yet.', max_length=20, null=True),
        ),
    ]
