import { USE_CASE_DESCRIPTIONS } from '../constants/useCases';

const OVERSIGHT_CHECKPOINTS = ['human_review', 'human_override', 'grading_validation', 'bias_audit', 'grading_fairness'];
const DATA_HANDLING_CHECKPOINTS = ['data_deidentified', 'data_storage', 'ferpa_compliance', 'data_classification'];

export function generateDisclosure(project) {
  const useCase = USE_CASE_DESCRIPTIONS[project.aiUseCase] || 'research activities';
  const toolNames = (project.aiTools || []).map(t => t.name);
  const completedCps = (project.checkpoints || []).filter(c => c.completed);
  const decisions = project.decisions || [];
  const date = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

  const sections = [];

  sections.push(`DISCLOSURE OF TECHNOLOGY USE\n\nActivity: ${project.name}\nDate: ${date}\n`);

  if (toolNames.length > 0) {
    sections.push(`Technology tools used: ${toolNames.join(', ')}.\n`);
  }

  let purpose = `These tools were used for ${useCase}`;
  if (project.description) {
    purpose += ` — specifically, ${project.description.toLowerCase().replace(/\.$/, '')}`;
  }
  purpose += `.\n`;
  sections.push(purpose);

  if (completedCps.length > 0) {
    const lines = completedCps.map(cp => {
      const suffix = cp.completedAt
        ? ` (${new Date(cp.completedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })})`
        : '';
      return `- ${cp.label}${suffix}`;
    });
    sections.push(`The following compliance steps were completed as part of this activity:\n${lines.join('\n')}\n`);
  }

  const oversightDecisions = decisions.filter(d => OVERSIGHT_CHECKPOINTS.includes(d.checkpoint));
  if (oversightDecisions.length > 0) {
    const lines = oversightDecisions.map(d => `- ${d.description}`);
    sections.push(`Human oversight measures:\n${lines.join('\n')}\n`);
  }

  const dataDecisions = decisions.filter(d => DATA_HANDLING_CHECKPOINTS.includes(d.checkpoint));
  if (dataDecisions.length > 0) {
    const lines = dataDecisions.map(d => `- ${d.description}`);
    sections.push(`Data handling:\n${lines.join('\n')}\n`);
  }

  const allFrameworks = [...new Set((project.checkpoints || []).flatMap(c => c.frameworks || []))];
  if (allFrameworks.length > 0) {
    sections.push(`This activity was reviewed against the following regulatory frameworks: ${allFrameworks.join(', ')}.\n`);
  }

  sections.push(`---\nGenerated by RAISE (Responsible AI Standards and Ethics)\nUniversity of South Florida`);

  return sections.join('\n');
}
